"""baseline

Revision ID: 2a95f04d8f10
Revises: 
Create Date: 2026-07-19 22:27:19.228375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a95f04d8f10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('weapons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('portrait_url', sa.String(), nullable=True),
    sa.Column('currency', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('abilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bonuses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('classes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('world', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discord_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('equipment', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id', 'guild_id', name=op.f('pk_actors'))
    )
    op.create_index(op.f('ix_actors_guild_id'), 'actors', ['guild_id'], unique=False)
    op.create_index(op.f('ix_actors_id'), 'actors', ['id'], unique=False)
    op.create_index(op.f('ix_actors_name'), 'actors', ['name'], unique=False)
    op.create_table('campaign',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('starting_level', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('session_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('voice_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign'))
    )
    op.create_index(op.f('ix_campaign_guild_id'), 'campaign', ['guild_id'], unique=False)
    op.create_index(op.f('ix_campaign_name'), 'campaign', ['name'], unique=False)
    op.create_table('downtime',
    sa.Column('player_message_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('player_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('gm_custom_id', sa.String(), nullable=False),
    sa.Column('gm_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('gm_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('player_message_id', name=op.f('pk_downtime'))
    )
    op.create_index(op.f('ix_downtime_guild_id'), 'downtime', ['guild_id'], unique=False)
    op.create_index(op.f('ix_downtime_player_message_id'), 'downtime', ['player_message_id'], unique=False)
    op.create_table('game_master',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('default_campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_master'))
    )
    op.create_index(op.f('ix_game_master_id'), 'game_master', ['id'], unique=False)
    op.create_table('gold_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('change', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'actor_id', 'guild_id', name=op.f('pk_gold_ledger'))
    )
    op.create_table('guild_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gm_role_id', sa.BigInteger(), nullable=False),
    sa.Column('gm_xp', sa.Integer(), nullable=False),
    sa.Column('session_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('downtime_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('scheduling_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('voice_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('subscription', sa.Enum('none', 'supporter', 'exempt', name='subscription'), nullable=False),
    sa.Column('foundry_hostname', sa.String(), nullable=False),
    sa.Column('auth_token', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('starting_level', sa.Integer(), nullable=False),
    sa.Column('combat_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('downtime_gm_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('rollcall_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('rollcall_role_id', sa.BigInteger(), nullable=True),
    sa.Column('rollcall_day', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='day'), nullable=True),
    sa.Column('rollcall_time', sa.Time(), nullable=True),
    sa.Column('pending_xp', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_indexed_message_id', sa.BigInteger(), nullable=True),
    sa.Column('roll_discord_to_foundry', sa.Boolean(), nullable=False),
    sa.Column('rollcall_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guild_settings'))
    )
    op.create_index(op.f('ix_guild_settings_auth_token'), 'guild_settings', ['auth_token'], unique=False)
    op.create_index(op.f('ix_guild_settings_id'), 'guild_settings', ['id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('system', sa.String(), nullable=False),
    sa.Column('min_pc_count', sa.Integer(), nullable=False),
    sa.Column('max_pc_count', sa.Integer(), nullable=False),
    sa.Column('gm_xp', sa.Integer(), nullable=False),
    sa.Column('hook', sa.String(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gm_id', sa.BigInteger(), nullable=True),
    sa.Column('gm_pc', sa.String(), nullable=True),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_or_thread_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_override', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('pcs', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('pcs_standby', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_missions'))
    )
    op.create_table('storage_expenses',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('standing', sa.String(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_storage_expenses'))
    )
    op.create_index(op.f('ix_storage_expenses_date'), 'storage_expenses', ['date'], unique=False)
    op.create_table('xp_adjustments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_adjustments')),
    sa.UniqueConstraint('guild_id', 'actor_id', 'comment', name='unique_guild_actor_comment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xp_adjustments')
    op.drop_index(op.f('ix_storage_expenses_date'), table_name='storage_expenses')
    op.drop_table('storage_expenses')
    op.drop_table('missions')
    op.drop_index(op.f('ix_guild_settings_id'), table_name='guild_settings')
    op.drop_index(op.f('ix_guild_settings_auth_token'), table_name='guild_settings')
    op.drop_table('guild_settings')
    op.drop_table('gold_ledger')
    op.drop_index(op.f('ix_game_master_id'), table_name='game_master')
    op.drop_table('game_master')
    op.drop_index(op.f('ix_downtime_player_message_id'), table_name='downtime')
    op.drop_index(op.f('ix_downtime_guild_id'), table_name='downtime')
    op.drop_table('downtime')
    op.drop_index(op.f('ix_campaign_name'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_guild_id'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_actors_name'), table_name='actors')
    op.drop_index(op.f('ix_actors_id'), table_name='actors')
    op.drop_index(op.f('ix_actors_guild_id'), table_name='actors')
    op.drop_table('actors')
    # autogenerate does not emit drops for the enum types created by
    # create_table above; without these a downgrade/upgrade cycle fails.
    sa.Enum(name='subscription').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='day').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
